---
Name: ecommerce_newsletter_campaign_monitor
Before: 'app/*'
After: 'framework/*','cms/*','ecommerce/*'
---
Sunnysideup\Ecommerce\Forms\OrderForm:
  extensions:
    - Sunnysideup\EcommerceMailchimpSignup\Model\Forms\EcommerceMailchimpSignupDecoratorFormFixes
Sunnysideup\Ecommerce\Model\Config\EcommerceDBConfig:
  extensions:
    - Sunnysideup\EcommerceMailchimpSignup\Model\Config\EcommerceMailchimpSignupDecoratorConfigFixes
SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\EcommerceMailchimpSignup\Model\Security\EcommerceMailchimpSignupMemberExtension
