---
Name: ecommerce_newsletter_campaign_monitor
Before: 'app/*'
After: 'framework/*','cms/*','ecommerce/*'
---
OrderForm:
  extensions:
    - EcommerceMailchimpSignupDecoratorFormFixes

EcommerceDBConfig:
  extensions:
    - EcommerceMailchimpSignupDecoratorConfigFixes

SilverStripe\Security\Member:
  extensions:
    - EcommerceMailchimpSignupMemberExtension
